# Generated by Django 3.1.5 on 2021-01-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0007_auto_20210116_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
