# Generated by Django 3.1.5 on 2021-01-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0008_libro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad',
            field=models.SmallIntegerField(default=1, verbose_name='Cantidad o Stock'),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='libros/', verbose_name='Imagen'),
        ),
    ]
