# Generated by Django 3.1.5 on 2021-01-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0009_auto_20210118_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad o Stock'),
        ),
    ]
